export const DRAW_PLAYER_STACK = 'DRAW_PLAYER_STACK';
export const PLAY_PLAYER_PLAYZONE = 'PLAY_PLAYER_PLAYZONE';
export const GET_PLAYERS_CARD = 'GET_PLAYERS_CARD';
export const NEXT_PLAYER = 'NEXT_PLAYER';
export const SET_SOUND = 'SET_SOUND';
export const NEW_SEQUENCE = 'NEW_SEQUENCE';
export const OPEN_SELECTED_CARD_MODAL = 'OPEN_SELECTED_CARD_MODAL';
export const SET_IA_COOP = 'SET_IA_COOP';